import fs from "fs";
import crypto from "crypto";
import path from "path";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import {
  categories,
  localLinePackageMeta,
  packages,
  productPricingProfiles,
  products,
  productSales,
  vendors
} from "../schema.js";
import {
  computeProductPricingSnapshot,
  isSourcePricingVendor
} from "../lib/productPricing.js";
import { ensureLocalLineSyncSchema, ensureProductPricingSchema, getDb, isMissingTableError } from "../db.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../../../");
const args = process.argv.slice(2);
const GOOGLE_PRICELIST_VENDOR_KEYWORDS = ["deck family farm", "creamy cow", "hyland"];

const ORDERED_COLUMN_NAMES = [
  "id",
  "localLineProductID",
  "category",
  "vendor",
  "productName",
  "retailSalesPrice",
  "dff_unit_of_measure",
  "packageName",
  "lowest_weight",
  "highest_weight",
  "sale",
  "saleDiscount",
  "squareSalePrice",
  "packageCount",
  "description",
  "FFCSAFactor",
  "avgWeightUsed",
  "packageQuantityUsed",
  "ffcsaPurchasePrice",
  "ffcsaMemberSalesPrice",
  "memberMarkup",
  "track_inventory",
  "visible",
  "remoteSyncStatus",
  "remoteSyncedAt"
];
const INTRO_NOTE_ROW_INDEX = 14;
const COLUMN_INDEX_BY_NAME = new Map(ORDERED_COLUMN_NAMES.map((name, index) => [name, index]));
const PRICE_SHEET_CURRENCY_COLUMNS = [
  "retailSalesPrice",
  "squareSalePrice",
  "ffcsaPurchasePrice",
  "ffcsaMemberSalesPrice"
];
const PRICE_SHEET_PERCENT_COLUMNS = [
  "FFCSAFactor",
  "memberMarkup",
  "saleDiscount"
];
const PRICE_SHEET_NUMBER_COLUMNS = [
  { key: "avgWeightUsed", pattern: "0.000" },
  { key: "packageQuantityUsed", pattern: "0" },
  { key: "packageCount", pattern: "0" }
];

function hasFlag(flag) {
  return args.includes(`--${flag}`);
}

function getArg(name) {
  const prefix = `--${name}=`;
  const value = args.find((arg) => arg.startsWith(prefix));
  return value ? value.slice(prefix.length) : null;
}

function resolveFromRepoRoot(targetPath) {
  if (!targetPath) return targetPath;
  return path.isAbsolute(targetPath)
    ? targetPath
    : path.resolve(repoRoot, targetPath);
}

function base64UrlEncode(input) {
  const buffer = Buffer.isBuffer(input) ? input : Buffer.from(input);
  return buffer
    .toString("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");
}

function columnIndexToLetter(index) {
  let column = "";
  let remainder = index;
  while (remainder > 0) {
    const letterIndex = (remainder - 1) % 26;
    column = String.fromCharCode(65 + letterIndex) + column;
    remainder = Math.floor((remainder - 1) / 26);
  }
  return column;
}

function getColumnLetterByName(columnName) {
  const index = COLUMN_INDEX_BY_NAME.get(columnName);
  if (!Number.isFinite(index)) {
    throw new Error(`Unknown Google pricelist column: ${columnName}`);
  }
  return columnIndexToLetter(index + 1);
}

function toNumber(value) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : null;
}

function toBooleanLabel(value) {
  return value ? "True" : "False";
}

function formatDateTime(value) {
  if (!value) return "";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString();
}

function toSheetValue(value) {
  return value === null || typeof value === "undefined" ? "" : value;
}

function flattenSheetText(value) {
  return String(value || "")
    .replace(/<br\s*\/?>/gi, " ")
    .replace(/<\/p>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/gi, " ")
    .replace(/&amp;/gi, "&")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizeVendorName(value) {
  return String(value || "").trim().toLowerCase();
}

function normalizeSheetTitle(value) {
  return String(value || "").trim().toLowerCase();
}

function isMembershipCategoryName(value) {
  return String(value || "").trim().toLowerCase() === "membership";
}

export function isGooglePricelistVendorName(name) {
  const normalized = normalizeVendorName(name);
  return GOOGLE_PRICELIST_VENDOR_KEYWORDS.some((keyword) => normalized.includes(keyword));
}

function buildPackageSummary(packageRows = [], unitOfMeasure = "each") {
  return packageRows
    .map((row) => {
      const details = [];
      if (unitOfMeasure === "lbs" && toNumber(row.averageWeight) !== null && Number(row.averageWeight) > 0) {
        details.push(`${row.averageWeight} lb avg`);
      }
      if (row.quantity > 1) details.push(`${row.quantity} ea`);
      return `${row.name || `Package ${row.id}`}${details.length ? ` (${details.join(" · ")})` : ""}`;
    })
    .join(", ");
}

function buildIntroductionValues(metadata) {
  return [
    ["Master Pricelist - Full Farm CSA"],
    ["Generated from the store pricing snapshot and synced automatically."],
    [],
    ["Metadata"],
    ["Sync time (UTC)", metadata.syncTimeUtc],
    ["Environment", metadata.environment],
    ["Generated by", "apps/api/scripts/exportMasterPricelist.js"],
    ["Source", "Store tables: products, packages, product_pricing_profiles, product_sales"],
    ["Sort order", "category, productName"],
    ["Google sheet", metadata.spreadsheetSummary],
    ["Sheets included", "Introduction, prices"],
    ["Vendor filter", metadata.vendorSummary],
    [],
    ["Notes"],
    ["Highlight note", "Rows highlighted in yellow show products with price changes in the last 2 weeks."],
    ["retailSalesPrice", "DFF source price from the store pricing profile"],
    ["FFCSAFactor", "FFCSA factor used only in the FFCSA online-store purchase price formula"],
    ["avgWeightUsed", "For weight-based products, the sheet uses the average of lowest_weight and highest_weight"],
    ["packageQuantityUsed", "For each-based products, the sheet uses this package quantity in the purchase price formula"],
    ["packageName", "Combined package summary for the product"],
    ["squareSalePrice", "Shown only for sale items. It is the Square / farmers-market sell price and is calculated from retailSalesPrice with the sale discount only."],
    ["ffcsaPurchasePrice", "Derived base package price before list markups"],
    ["ffcsaMemberSalesPrice", "Derived FFCSA online-store member-facing price"],
    ["Sync behavior", "Google sync replaces all data in the configured prices tab"]
  ];
}

function toTimestamp(value) {
  if (!value) return 0;
  const timestamp = new Date(value).getTime();
  return Number.isFinite(timestamp) ? timestamp : 0;
}

function hasRecentPriceOrSaleChange(profile, saleRow, windowDays = 14) {
  const cutoff = Date.now() - windowDays * 24 * 60 * 60 * 1000;
  return toTimestamp(profile?.priceChangedAt) >= cutoff;
}

async function getServiceAccountAccessToken(credentialsPath) {
  const resolvedPath = resolveFromRepoRoot(credentialsPath);
  const credentials = JSON.parse(fs.readFileSync(resolvedPath, "utf8"));
  const issuedAt = Math.floor(Date.now() / 1000);
  const expiresAt = issuedAt + 60 * 60;

  const header = { alg: "RS256", typ: "JWT" };
  const claimSet = {
    iss: credentials.client_email,
    scope: "https://www.googleapis.com/auth/spreadsheets",
    aud: credentials.token_uri || "https://oauth2.googleapis.com/token",
    iat: issuedAt,
    exp: expiresAt
  };

  const unsignedToken = `${base64UrlEncode(JSON.stringify(header))}.${base64UrlEncode(JSON.stringify(claimSet))}`;
  const signature = crypto
    .createSign("RSA-SHA256")
    .update(unsignedToken)
    .sign(credentials.private_key);
  const signedJwt = `${unsignedToken}.${base64UrlEncode(signature)}`;

  const response = await fetch(credentials.token_uri, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
      assertion: signedJwt
    })
  });

  if (!response.ok) {
    throw new Error(`Google token request failed: ${response.status} ${response.statusText}`);
  }

  const payload = await response.json();
  return payload.access_token;
}

async function googleSheetRequest(url, options) {
  const response = await fetch(url, options);
  if (response.ok) {
    return response;
  }

  const text = await response.text();
  throw new Error(`Google Sheets request failed: ${response.status} ${response.statusText} ${text}`);
}

async function getGoogleSheetInfo({ accessToken, spreadsheetId, sheetName }) {
  const response = await googleSheetRequest(
    `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}?fields=sheets.properties`,
    {
      headers: {
        Authorization: `Bearer ${accessToken}`
      }
    }
  );

  const payload = await response.json();
  const sheets = payload.sheets || [];
  const exactMatch = sheets.find(
    (sheet) => String(sheet?.properties?.title || "") === String(sheetName)
  );
  const matchingSheet =
    exactMatch ||
    sheets.find(
      (sheet) =>
        normalizeSheetTitle(sheet?.properties?.title) === normalizeSheetTitle(sheetName)
    );

  if (!matchingSheet?.properties?.sheetId && matchingSheet?.properties?.sheetId !== 0) {
    const availableTabs = sheets
      .map((sheet) => sheet?.properties?.title)
      .filter(Boolean)
      .join(", ");
    throw new Error(
      `Google Sheet tab not found: ${sheetName}${availableTabs ? ` (available: ${availableTabs})` : ""}`
    );
  }

  return {
    sheetId: Number(matchingSheet.properties.sheetId),
    sheetName: String(matchingSheet.properties.title || sheetName)
  };
}

async function formatGoogleSheetHeader({
  accessToken,
  spreadsheetId,
  sheetName,
  columnCount
}) {
  const { sheetId } = await getGoogleSheetInfo({ accessToken, spreadsheetId, sheetName });
  const safeColumnCount = Math.max(Number(columnCount) || 1, 1);

  await googleSheetRequest(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}:batchUpdate`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      requests: [
        {
          updateSheetProperties: {
            properties: {
              sheetId,
              gridProperties: {
                frozenRowCount: 1
              }
            },
            fields: "gridProperties.frozenRowCount"
          }
        },
        {
          repeatCell: {
            range: {
              sheetId,
              startRowIndex: 0,
              endRowIndex: 1,
              startColumnIndex: 0,
              endColumnIndex: safeColumnCount
            },
            cell: {
              userEnteredFormat: {
                textFormat: {
                  bold: true
                }
              }
            },
            fields: "userEnteredFormat.textFormat.bold"
          }
        }
      ]
    })
  });
}

async function formatGooglePricelistColumns({
  accessToken,
  spreadsheetId,
  sheetName,
  rowCount
}) {
  const { sheetId } = await getGoogleSheetInfo({ accessToken, spreadsheetId, sheetName });
  const safeRowCount = Math.max(Number(rowCount) || 1, 1);
  const requests = [];

  PRICE_SHEET_CURRENCY_COLUMNS.forEach((columnName) => {
    const index = COLUMN_INDEX_BY_NAME.get(columnName);
    if (!Number.isFinite(index)) return;
    requests.push({
      repeatCell: {
        range: {
          sheetId,
          startRowIndex: 1,
          endRowIndex: safeRowCount,
          startColumnIndex: index,
          endColumnIndex: index + 1
        },
        cell: {
          userEnteredFormat: {
            numberFormat: {
              type: "CURRENCY",
              pattern: "$#,##0.00"
            }
          }
        },
        fields: "userEnteredFormat.numberFormat"
      }
    });
  });

  PRICE_SHEET_PERCENT_COLUMNS.forEach((columnName) => {
    const index = COLUMN_INDEX_BY_NAME.get(columnName);
    if (!Number.isFinite(index)) return;
    requests.push({
      repeatCell: {
        range: {
          sheetId,
          startRowIndex: 1,
          endRowIndex: safeRowCount,
          startColumnIndex: index,
          endColumnIndex: index + 1
        },
        cell: {
          userEnteredFormat: {
            numberFormat: {
              type: "PERCENT",
              pattern: "0.00%"
            }
          }
        },
        fields: "userEnteredFormat.numberFormat"
      }
    });
  });

  PRICE_SHEET_NUMBER_COLUMNS.forEach(({ key, pattern }) => {
    const index = COLUMN_INDEX_BY_NAME.get(key);
    if (!Number.isFinite(index)) return;
    requests.push({
      repeatCell: {
        range: {
          sheetId,
          startRowIndex: 1,
          endRowIndex: safeRowCount,
          startColumnIndex: index,
          endColumnIndex: index + 1
        },
        cell: {
          userEnteredFormat: {
            numberFormat: {
              type: "NUMBER",
              pattern
            }
          }
        },
        fields: "userEnteredFormat.numberFormat"
      }
    });
  });

  if (!requests.length) return;

  await googleSheetRequest(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}:batchUpdate`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ requests })
  });
}

async function formatGoogleSheetHighlightedRows({
  accessToken,
  spreadsheetId,
  sheetName,
  columnCount,
  rowCount,
  highlightedRowIndices = []
}) {
  const { sheetId } = await getGoogleSheetInfo({ accessToken, spreadsheetId, sheetName });
  const safeColumnCount = Math.max(Number(columnCount) || 1, 1);
  const safeRowCount = Math.max(Number(rowCount) || 1, 1);
  const requests = [];

  if (safeRowCount > 1) {
    requests.push({
      repeatCell: {
        range: {
          sheetId,
          startRowIndex: 1,
          endRowIndex: safeRowCount,
          startColumnIndex: 0,
          endColumnIndex: safeColumnCount
        },
        cell: {
          userEnteredFormat: {
            backgroundColor: {
              red: 1,
              green: 1,
              blue: 1
            }
          }
        },
        fields: "userEnteredFormat.backgroundColor"
      }
    });
  }

  highlightedRowIndices.forEach((rowIndex) => {
    if (!Number.isFinite(rowIndex) || rowIndex < 1 || rowIndex >= safeRowCount) return;
    requests.push({
      repeatCell: {
        range: {
          sheetId,
          startRowIndex: rowIndex,
          endRowIndex: rowIndex + 1,
          startColumnIndex: 0,
          endColumnIndex: safeColumnCount
        },
        cell: {
          userEnteredFormat: {
            backgroundColor: {
              red: 1,
              green: 0.949,
              blue: 0.6
            }
          }
        },
        fields: "userEnteredFormat.backgroundColor"
      }
    });
  });

  if (!requests.length) return;

  await googleSheetRequest(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}:batchUpdate`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({ requests })
  });
}

async function formatGoogleSheetNoteRow({
  accessToken,
  spreadsheetId,
  sheetName,
  rowIndex,
  columnCount
}) {
  const { sheetId } = await getGoogleSheetInfo({ accessToken, spreadsheetId, sheetName });
  const safeColumnCount = Math.max(Number(columnCount) || 1, 1);
  const safeRowIndex = Math.max(Number(rowIndex) || 0, 0);

  await googleSheetRequest(`https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}:batchUpdate`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      requests: [
        {
          repeatCell: {
            range: {
              sheetId,
              startRowIndex: safeRowIndex,
              endRowIndex: safeRowIndex + 1,
              startColumnIndex: 0,
              endColumnIndex: safeColumnCount
            },
            cell: {
              userEnteredFormat: {
                backgroundColor: {
                  red: 1,
                  green: 0.949,
                  blue: 0.6
                },
                textFormat: {
                  bold: true
                }
              }
            },
            fields: "userEnteredFormat.backgroundColor,userEnteredFormat.textFormat.bold"
          }
        }
      ]
    })
  });
}

async function updateGoogleSheet({ accessToken, spreadsheetId, sheetName, values }) {
  const sheetInfo = await getGoogleSheetInfo({ accessToken, spreadsheetId, sheetName });
  const resolvedSheetName = sheetInfo.sheetName;
  const encodedSheet = encodeURIComponent(resolvedSheetName);
  const columnCount = values.reduce((max, row) => Math.max(max, row?.length || 0), 1);
  const rowCount = values.length || 1;
  const endColumn = columnIndexToLetter(columnCount);
  const range = `${resolvedSheetName}!A1:${endColumn}${rowCount}`;
  const baseUrl = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values`;

  await googleSheetRequest(`${baseUrl}/${encodedSheet}:clear`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({})
  });

  await googleSheetRequest(
    `${baseUrl}/${encodeURIComponent(range)}?valueInputOption=USER_ENTERED`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        range,
        majorDimension: "ROWS",
        values
      })
    }
  );

  return { columnCount, rowCount, sheetName: resolvedSheetName };
}

async function syncPricelistToGoogleSheet(sheetValues, introductionValues) {
  const credentialsPath = process.env.GOOGLE_APPLICATION_CREDENTIALS;
  const spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID;
  const sheetName = process.env.GOOGLE_SHEETS_TAB_NAME || "prices";

  if (!credentialsPath || !spreadsheetId || !sheetName) {
    throw new Error("Missing GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_SHEETS_SPREADSHEET_ID, or GOOGLE_SHEETS_TAB_NAME.");
  }

  const accessToken = await getServiceAccountAccessToken(credentialsPath);
  const priceSheetUpdate = await updateGoogleSheet({
    accessToken,
    spreadsheetId,
    sheetName,
    values: sheetValues
  });
  await formatGoogleSheetHeader({
    accessToken,
    spreadsheetId,
    sheetName,
    columnCount: priceSheetUpdate.columnCount
  });
  await formatGooglePricelistColumns({
    accessToken,
    spreadsheetId,
    sheetName,
    rowCount: priceSheetUpdate.rowCount
  });
  await formatGoogleSheetHighlightedRows({
    accessToken,
    spreadsheetId,
    sheetName,
    columnCount: priceSheetUpdate.columnCount,
    rowCount: priceSheetUpdate.rowCount,
    highlightedRowIndices: sheetValues.highlightedRowIndices || []
  });
  console.log(`Google Sheet updated: ${spreadsheetId} (${sheetName})`);

  const introSheetName = process.env.GOOGLE_SHEETS_INTRO_TAB_NAME || "Introduction";
  const introSheetUpdate = await updateGoogleSheet({
    accessToken,
    spreadsheetId,
    sheetName: introSheetName,
    values: introductionValues
  });
  await formatGoogleSheetNoteRow({
    accessToken,
    spreadsheetId,
    sheetName: introSheetName,
    rowIndex: introductionValues.noteRowIndex || 0,
    columnCount: introSheetUpdate.columnCount
  });
  console.log(`Google Sheet updated: ${spreadsheetId} (${introSheetName})`);
}

async function buildSheetValues({ vendorNameMatcher = null } = {}) {
  const db = getDb();
  await ensureLocalLineSyncSchema();
  await ensureProductPricingSchema();

  const [
    productRows,
    packageRows,
    profileRows,
    saleRows,
    categoryRows,
    vendorRows
  ] = await Promise.all([
    db.select().from(products),
    db.select().from(packages),
    db.select().from(productPricingProfiles),
    db.select().from(productSales),
    db.select().from(categories),
    db.select().from(vendors)
  ]);

  let packageMetaRows = [];
  try {
    packageMetaRows = await db.select().from(localLinePackageMeta);
  } catch (error) {
    if (!isMissingTableError(error, "local_line_package_meta")) {
      throw error;
    }
  }

  const categoryMap = new Map(categoryRows.map((row) => [Number(row.id), row.name || "Uncategorized"]));
  const vendorMap = new Map(vendorRows.map((row) => [Number(row.id), row]));
  const saleByProductId = new Map(saleRows.map((row) => [Number(row.productId), row]));
  const profileByProductId = new Map(profileRows.map((row) => [Number(row.productId), row]));
  const packageMetaByPackageId = new Map(packageMetaRows.map((row) => [Number(row.packageId), row]));
  const packagesByProductId = packageRows.reduce((acc, row) => {
    const key = Number(row.productId);
    const list = acc.get(key) || [];
    list.push(row);
    acc.set(key, list);
    return acc;
  }, new Map());

  const matchedVendorNames = new Set();
  const filteredProducts = productRows
    .filter((row) => {
      if (row.isDeleted) return false;
      if (isMembershipCategoryName(categoryMap.get(Number(row.categoryId)))) return false;
      if (typeof vendorNameMatcher !== "function") return true;
      const vendorName = vendorMap.get(Number(row.vendorId))?.name || "";
      const matches = vendorNameMatcher(vendorName, row);
      if (matches) {
        matchedVendorNames.add(vendorName);
      }
      return matches;
    })
    .slice()
    .sort((left, right) => {
      const leftCategory = String(categoryMap.get(Number(left.categoryId)) || "Uncategorized");
      const rightCategory = String(categoryMap.get(Number(right.categoryId)) || "Uncategorized");
      return (
        leftCategory.localeCompare(rightCategory) ||
        String(left.name || "").localeCompare(String(right.name || ""))
      );
    });

  const sheetValues = [ORDERED_COLUMN_NAMES];
  const highlightedRowIndices = [];

  for (const product of filteredProducts) {
    const productId = Number(product.id);
    const snapshot = computeProductPricingSnapshot({
      product,
      packages: packagesByProductId.get(productId) || [],
      packageMetaByPackageId,
      vendor: vendorMap.get(Number(product.vendorId)) || null,
      profile: profileByProductId.get(productId) || {
        productId,
        onSale: saleByProductId.get(productId)?.onSale ?? 0,
        saleDiscount: saleByProductId.get(productId)?.saleDiscount ?? 0
      }
    });

    const vendor = vendorMap.get(Number(product.vendorId)) || null;
    const usesSourcePricing = isSourcePricingVendor(vendor);
    const saleRow = saleByProductId.get(productId) || null;
    const chosenPackageRow =
      snapshot.packageRows
        .filter((row) => toNumber(row.basePrice) !== null)
        .sort((left, right) => Number(left.basePrice) - Number(right.basePrice))[0] || null;
    const rowNumber = sheetValues.length + 1;
    const retailSalesPriceCol = getColumnLetterByName("retailSalesPrice");
    const unitOfMeasureCol = getColumnLetterByName("dff_unit_of_measure");
    const lowestWeightCol = getColumnLetterByName("lowest_weight");
    const highestWeightCol = getColumnLetterByName("highest_weight");
    const sourceMultiplierCol = getColumnLetterByName("FFCSAFactor");
    const avgWeightUsedCol = getColumnLetterByName("avgWeightUsed");
    const packageQuantityUsedCol = getColumnLetterByName("packageQuantityUsed");
    const purchasePriceCol = getColumnLetterByName("ffcsaPurchasePrice");
    const memberMarkupCol = getColumnLetterByName("memberMarkup");
    const saleCol = getColumnLetterByName("sale");
    const saleDiscountCol = getColumnLetterByName("saleDiscount");
    const customerSaleShareFormula = `IF(${saleCol}${rowNumber},${saleDiscountCol}${rowNumber},0)`;
    const purchaseFormula = `=IF(LOWER(${unitOfMeasureCol}${rowNumber})="lbs",IF(OR(${retailSalesPriceCol}${rowNumber}="",${avgWeightUsedCol}${rowNumber}=""),"",ROUND(${retailSalesPriceCol}${rowNumber}*${avgWeightUsedCol}${rowNumber}*${sourceMultiplierCol}${rowNumber},2)),IF(OR(${retailSalesPriceCol}${rowNumber}="",${packageQuantityUsedCol}${rowNumber}=""),"",ROUND(${retailSalesPriceCol}${rowNumber}*${packageQuantityUsedCol}${rowNumber}*${sourceMultiplierCol}${rowNumber},2)))`;
    const memberFormulaBody = `IF(OR(${purchasePriceCol}${rowNumber}="",${memberMarkupCol}${rowNumber}=""),"",ROUND(${purchasePriceCol}${rowNumber}*(1+${memberMarkupCol}${rowNumber})*(1-${customerSaleShareFormula}),2))`;
    const memberFormula = `=${memberFormulaBody}`;
    const squareSalePriceFormulaBody = `IF(${retailSalesPriceCol}${rowNumber}="","",ROUND(${retailSalesPriceCol}${rowNumber}*(1-${customerSaleShareFormula}),2))`;
    const squareSalePriceFormula = `=IF(${saleCol}${rowNumber},${squareSalePriceFormulaBody},"")`;
    const isWeightBasedSourcePricing =
      usesSourcePricing && String(snapshot.profile.unitOfMeasure || "").toLowerCase() === "lbs";
    const isEachBasedSourcePricing =
      usesSourcePricing && String(snapshot.profile.unitOfMeasure || "").toLowerCase() !== "lbs";
    const saleEnabled = Boolean(snapshot.profile.onSale);
    const rowValues = {
      id: productId,
      localLineProductID: productId,
      category: categoryMap.get(Number(product.categoryId)) || "Uncategorized",
      vendor: vendor?.name || "",
      productName: product.name || "",
      packageName: buildPackageSummary(snapshot.packageRows, snapshot.profile.unitOfMeasure),
      retailSalesPrice: usesSourcePricing ? snapshot.profile.sourceUnitPrice : "",
      lowest_weight: isWeightBasedSourcePricing ? snapshot.profile.minWeight : "",
      highest_weight: isWeightBasedSourcePricing ? snapshot.profile.maxWeight : "",
      dff_unit_of_measure: usesSourcePricing ? snapshot.profile.unitOfMeasure : "",
      sale: saleEnabled ? "TRUE" : "",
      saleDiscount: saleEnabled ? snapshot.profile.saleDiscount : "",
      squareSalePrice: saleEnabled ? squareSalePriceFormula : "",
      packageCount: snapshot.packageRows.length,
      description: flattenSheetText(product.description),
      FFCSAFactor: usesSourcePricing ? snapshot.profile.sourceMultiplier : "",
      avgWeightUsed:
        isWeightBasedSourcePricing
          ? `=IF(AND(${lowestWeightCol}${rowNumber}<>"",${highestWeightCol}${rowNumber}<>""),AVERAGE(${lowestWeightCol}${rowNumber},${highestWeightCol}${rowNumber}),IF(${lowestWeightCol}${rowNumber}<>"",${lowestWeightCol}${rowNumber},IF(${highestWeightCol}${rowNumber}<>"",${highestWeightCol}${rowNumber},"")))`
          : "",
      packageQuantityUsed:
        isEachBasedSourcePricing
          ? (chosenPackageRow ? Number(chosenPackageRow.quantity || 1) : 1)
          : "",
      ffcsaPurchasePrice: purchaseFormula,
      ffcsaMemberSalesPrice: memberFormula,
      memberMarkup: snapshot.profile.memberMarkup,
      track_inventory: toBooleanLabel(Boolean(product.trackInventory)),
      visible: toBooleanLabel(Boolean(product.visible)),
      remoteSyncStatus: snapshot.profile.remoteSyncStatus || "",
      remoteSyncedAt: formatDateTime(snapshot.profile.remoteSyncedAt)
    };

    if (hasRecentPriceOrSaleChange(profileByProductId.get(productId) || null, saleRow)) {
      highlightedRowIndices.push(sheetValues.length);
    }

    sheetValues.push(
      ORDERED_COLUMN_NAMES.map((column) => toSheetValue(rowValues[column]))
    );
  }

  Object.defineProperty(sheetValues, "highlightedRowIndices", {
    value: highlightedRowIndices,
    enumerable: false,
    configurable: false,
    writable: false
  });

  return {
    sheetValues,
    rowCount: Math.max(sheetValues.length - 1, 0),
    vendorNames: [...matchedVendorNames].sort((left, right) => left.localeCompare(right)),
    highlightedRowCount: highlightedRowIndices.length
  };
}

export async function exportMasterPricelist({
  nodeEnv = process.env.NODE_ENV || "production",
  dryRun = false,
  skipGoogle = false,
  vendorNameMatcher = null,
  spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID || "",
  tabName = process.env.GOOGLE_SHEETS_TAB_NAME || "prices"
} = {}) {
  const spreadsheetSummary = spreadsheetId
    ? `${spreadsheetId} (tab: ${tabName})`
    : "Not configured";

  const { sheetValues, rowCount, vendorNames, highlightedRowCount } = await buildSheetValues({ vendorNameMatcher });
  const vendorSummary = vendorNames.length ? vendorNames.join(", ") : "All vendors";
  const introductionValues = buildIntroductionValues({
    syncTimeUtc: new Date().toISOString(),
    environment: nodeEnv,
    spreadsheetSummary,
    vendorSummary
  });
  Object.defineProperty(introductionValues, "noteRowIndex", {
    value: INTRO_NOTE_ROW_INDEX,
    enumerable: false,
    configurable: false,
    writable: false
  });

  if (dryRun || skipGoogle) {
    return {
      mode: dryRun ? "dry-run" : "skip-google",
      nodeEnv,
      spreadsheetSummary,
      vendorNames,
      rowCount,
      highlightedRowCount,
      sampleRows: sheetValues.slice(0, 6)
    };
  }

  await syncPricelistToGoogleSheet(sheetValues, introductionValues);
  return {
    mode: "google-sync",
    nodeEnv,
    spreadsheetSummary,
    vendorNames,
    rowCount,
    highlightedRowCount
  };
}

async function main() {
  const envFile = resolveFromRepoRoot(getArg("env-file") || ".env");
  const nodeEnv =
    getArg("node-env") ||
    (path.basename(envFile).match(/^\.env\.(.+)$/) || [])[1] ||
    process.env.NODE_ENV ||
    "production";
  const dryRun = hasFlag("dry-run");
  const skipGoogle = hasFlag("skip-google");

  dotenv.config({ path: envFile });

  const summary = await exportMasterPricelist({
    nodeEnv,
    dryRun,
    skipGoogle
  });

  if (dryRun || skipGoogle) {
    console.log(
      JSON.stringify(
        {
          ...summary,
          envFile
        },
        null,
        2
      )
    );
    return;
  }

  console.log(`Exported ${summary.rowCount} rows to Google Sheets.`);
}

const isDirectExecution =
  process.argv[1] && path.resolve(process.argv[1]) === __filename;

if (isDirectExecution) {
  main().catch((error) => {
    console.error(error?.message || error);
    process.exit(1);
  });
}
