import fs from "fs";
import crypto from "crypto";
import path from "path";
import dotenv from "dotenv";
import { fileURLToPath } from "url";
import {
  categories,
  localLinePackageMeta,
  packages,
  productPricingProfiles,
  products,
  productSales,
  vendors
} from "../schema.js";
import { computeProductPricingSnapshot, isSourcePricingVendor } from "../lib/productPricing.js";
import { ensureLocalLineSyncSchema, getDb, isMissingTableError } from "../db.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, "../../../");
const args = process.argv.slice(2);
const GOOGLE_PRICELIST_VENDOR_KEYWORDS = ["deck family farm", "creamy cow", "hyland"];

const ORDERED_COLUMN_NAMES = [
  "id",
  "localLineProductID",
  "category",
  "vendor",
  "productName",
  "packageName",
  "retailSalesPrice",
  "lowest_weight",
  "highest_weight",
  "dff_unit_of_measure",
  "sourceMultiplier",
  "ffcsaPurchasePrice",
  "ffcsaMemberSalesPrice",
  "ffcsaGuestSalesPrice",
  "memberMarkup",
  "guestPercentOverRetail",
  "herdShareMarkup",
  "snapMarkup",
  "sale",
  "saleDiscount",
  "packageCount",
  "description",
  "track_inventory",
  "visible",
  "remoteSyncStatus",
  "remoteSyncedAt"
];

function hasFlag(flag) {
  return args.includes(`--${flag}`);
}

function getArg(name) {
  const prefix = `--${name}=`;
  const value = args.find((arg) => arg.startsWith(prefix));
  return value ? value.slice(prefix.length) : null;
}

function resolveFromRepoRoot(targetPath) {
  if (!targetPath) return targetPath;
  return path.isAbsolute(targetPath)
    ? targetPath
    : path.resolve(repoRoot, targetPath);
}

function base64UrlEncode(input) {
  const buffer = Buffer.isBuffer(input) ? input : Buffer.from(input);
  return buffer
    .toString("base64")
    .replace(/=/g, "")
    .replace(/\+/g, "-")
    .replace(/\//g, "_");
}

function columnIndexToLetter(index) {
  let column = "";
  let remainder = index;
  while (remainder > 0) {
    const letterIndex = (remainder - 1) % 26;
    column = String.fromCharCode(65 + letterIndex) + column;
    remainder = Math.floor((remainder - 1) / 26);
  }
  return column;
}

function toNumber(value) {
  const numeric = Number(value);
  return Number.isFinite(numeric) ? numeric : null;
}

function toBooleanLabel(value) {
  return value ? "True" : "False";
}

function formatDateTime(value) {
  if (!value) return "";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toISOString();
}

function toSheetValue(value) {
  return value === null || typeof value === "undefined" ? "" : value;
}

function normalizeVendorName(value) {
  return String(value || "").trim().toLowerCase();
}

export function isGooglePricelistVendorName(name) {
  const normalized = normalizeVendorName(name);
  return GOOGLE_PRICELIST_VENDOR_KEYWORDS.some((keyword) => normalized.includes(keyword));
}

function buildPackageSummary(packageRows = [], unitOfMeasure = "each") {
  return packageRows
    .map((row) => {
      const details = [];
      if (unitOfMeasure === "lbs" && toNumber(row.averageWeight) !== null && Number(row.averageWeight) > 0) {
        details.push(`${row.averageWeight} lb avg`);
      }
      if (row.quantity > 1) details.push(`${row.quantity} ea`);
      return `${row.name || `Package ${row.id}`}${details.length ? ` (${details.join(" · ")})` : ""}`;
    })
    .join(", ");
}

function buildIntroductionValues(metadata) {
  return [
    ["Master Pricelist - Full Farm CSA"],
    ["Generated from the store pricing snapshot and synced automatically."],
    [],
    ["Metadata"],
    ["Sync time (UTC)", metadata.syncTimeUtc],
    ["Environment", metadata.environment],
    ["Generated by", "apps/api/scripts/exportMasterPricelist.js"],
    ["Source", "Store tables: products, packages, product_pricing_profiles, product_sales"],
    ["Sort order", "category, productName"],
    ["Google sheet", metadata.spreadsheetSummary],
    ["Sheets included", "Introduction, prices"],
    ["Vendor filter", metadata.vendorSummary],
    [],
    ["Notes"],
    ["retailSalesPrice", "DFF source price from the store pricing profile"],
    ["packageName", "Combined package summary for the product"],
    ["ffcsaPurchasePrice", "Derived base package price before list markups"],
    ["ffcsaMemberSalesPrice", "Derived member-facing price"],
    ["ffcsaGuestSalesPrice", "Derived guest-facing price"],
    ["Sync behavior", "Google sync replaces all data in the configured prices tab"]
  ];
}

async function getServiceAccountAccessToken(credentialsPath) {
  const resolvedPath = resolveFromRepoRoot(credentialsPath);
  const credentials = JSON.parse(fs.readFileSync(resolvedPath, "utf8"));
  const issuedAt = Math.floor(Date.now() / 1000);
  const expiresAt = issuedAt + 60 * 60;

  const header = { alg: "RS256", typ: "JWT" };
  const claimSet = {
    iss: credentials.client_email,
    scope: "https://www.googleapis.com/auth/spreadsheets",
    aud: credentials.token_uri || "https://oauth2.googleapis.com/token",
    iat: issuedAt,
    exp: expiresAt
  };

  const unsignedToken = `${base64UrlEncode(JSON.stringify(header))}.${base64UrlEncode(JSON.stringify(claimSet))}`;
  const signature = crypto
    .createSign("RSA-SHA256")
    .update(unsignedToken)
    .sign(credentials.private_key);
  const signedJwt = `${unsignedToken}.${base64UrlEncode(signature)}`;

  const response = await fetch(credentials.token_uri, {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: new URLSearchParams({
      grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
      assertion: signedJwt
    })
  });

  if (!response.ok) {
    throw new Error(`Google token request failed: ${response.status} ${response.statusText}`);
  }

  const payload = await response.json();
  return payload.access_token;
}

async function googleSheetRequest(url, options) {
  const response = await fetch(url, options);
  if (response.ok) {
    return response;
  }

  const text = await response.text();
  throw new Error(`Google Sheets request failed: ${response.status} ${response.statusText} ${text}`);
}

async function updateGoogleSheet({ accessToken, spreadsheetId, sheetName, values }) {
  const encodedSheet = encodeURIComponent(sheetName);
  const columnCount = values.reduce((max, row) => Math.max(max, row?.length || 0), 1);
  const rowCount = values.length || 1;
  const endColumn = columnIndexToLetter(columnCount);
  const range = `${sheetName}!A1:${endColumn}${rowCount}`;
  const baseUrl = `https://sheets.googleapis.com/v4/spreadsheets/${spreadsheetId}/values`;

  await googleSheetRequest(`${baseUrl}/${encodedSheet}:clear`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json"
    },
    body: JSON.stringify({})
  });

  await googleSheetRequest(
    `${baseUrl}/${encodeURIComponent(range)}?valueInputOption=RAW`,
    {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify({
        range,
        majorDimension: "ROWS",
        values
      })
    }
  );
}

async function syncPricelistToGoogleSheet(sheetValues, introductionValues) {
  const credentialsPath = process.env.GOOGLE_APPLICATION_CREDENTIALS;
  const spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID;
  const sheetName = process.env.GOOGLE_SHEETS_TAB_NAME || "prices";

  if (!credentialsPath || !spreadsheetId || !sheetName) {
    throw new Error("Missing GOOGLE_APPLICATION_CREDENTIALS, GOOGLE_SHEETS_SPREADSHEET_ID, or GOOGLE_SHEETS_TAB_NAME.");
  }

  const accessToken = await getServiceAccountAccessToken(credentialsPath);
  await updateGoogleSheet({
    accessToken,
    spreadsheetId,
    sheetName,
    values: sheetValues
  });
  console.log(`Google Sheet updated: ${spreadsheetId} (${sheetName})`);

  const introSheetName = process.env.GOOGLE_SHEETS_INTRO_TAB_NAME || "Introduction";
  await updateGoogleSheet({
    accessToken,
    spreadsheetId,
    sheetName: introSheetName,
    values: introductionValues
  });
  console.log(`Google Sheet updated: ${spreadsheetId} (${introSheetName})`);
}

async function buildSheetValues({ vendorNameMatcher = null } = {}) {
  const db = getDb();
  await ensureLocalLineSyncSchema();

  const [
    productRows,
    packageRows,
    profileRows,
    saleRows,
    categoryRows,
    vendorRows
  ] = await Promise.all([
    db.select().from(products),
    db.select().from(packages),
    db.select().from(productPricingProfiles),
    db.select().from(productSales),
    db.select().from(categories),
    db.select().from(vendors)
  ]);

  let packageMetaRows = [];
  try {
    packageMetaRows = await db.select().from(localLinePackageMeta);
  } catch (error) {
    if (!isMissingTableError(error, "local_line_package_meta")) {
      throw error;
    }
  }

  const categoryMap = new Map(categoryRows.map((row) => [Number(row.id), row.name || "Uncategorized"]));
  const vendorMap = new Map(vendorRows.map((row) => [Number(row.id), row]));
  const saleByProductId = new Map(saleRows.map((row) => [Number(row.productId), row]));
  const profileByProductId = new Map(profileRows.map((row) => [Number(row.productId), row]));
  const packageMetaByPackageId = new Map(packageMetaRows.map((row) => [Number(row.packageId), row]));
  const packagesByProductId = packageRows.reduce((acc, row) => {
    const key = Number(row.productId);
    const list = acc.get(key) || [];
    list.push(row);
    acc.set(key, list);
    return acc;
  }, new Map());

  const matchedVendorNames = new Set();
  const filteredProducts = productRows
    .filter((row) => {
      if (row.isDeleted) return false;
      if (typeof vendorNameMatcher !== "function") return true;
      const vendorName = vendorMap.get(Number(row.vendorId))?.name || "";
      const matches = vendorNameMatcher(vendorName, row);
      if (matches) {
        matchedVendorNames.add(vendorName);
      }
      return matches;
    })
    .slice()
    .sort((left, right) => {
      const leftCategory = String(categoryMap.get(Number(left.categoryId)) || "Uncategorized");
      const rightCategory = String(categoryMap.get(Number(right.categoryId)) || "Uncategorized");
      return (
        leftCategory.localeCompare(rightCategory) ||
        String(left.name || "").localeCompare(String(right.name || ""))
      );
    });

  const sheetValues = [ORDERED_COLUMN_NAMES];

  for (const product of filteredProducts) {
    const productId = Number(product.id);
    const snapshot = computeProductPricingSnapshot({
      product,
      packages: packagesByProductId.get(productId) || [],
      packageMetaByPackageId,
      vendor: vendorMap.get(Number(product.vendorId)) || null,
      profile: profileByProductId.get(productId) || {
        productId,
        onSale: saleByProductId.get(productId)?.onSale ?? 0,
        saleDiscount: saleByProductId.get(productId)?.saleDiscount ?? 0
      }
    });

    const vendor = vendorMap.get(Number(product.vendorId)) || null;
    const usesSourcePricing = isSourcePricingVendor(vendor);
    const rowValues = {
      id: productId,
      localLineProductID: productId,
      category: categoryMap.get(Number(product.categoryId)) || "Uncategorized",
      vendor: vendor?.name || "",
      productName: product.name || "",
      packageName: buildPackageSummary(snapshot.packageRows, snapshot.profile.unitOfMeasure),
      retailSalesPrice: usesSourcePricing ? snapshot.profile.sourceUnitPrice : "",
      lowest_weight: usesSourcePricing ? snapshot.profile.minWeight : "",
      highest_weight: usesSourcePricing ? snapshot.profile.maxWeight : "",
      dff_unit_of_measure: usesSourcePricing ? snapshot.profile.unitOfMeasure : "",
      sourceMultiplier: usesSourcePricing ? snapshot.profile.sourceMultiplier : "",
      ffcsaPurchasePrice: snapshot.basePrice,
      ffcsaMemberSalesPrice: snapshot.memberPrice,
      ffcsaGuestSalesPrice: snapshot.guestPrice,
      memberMarkup: snapshot.profile.memberMarkup,
      guestPercentOverRetail: snapshot.profile.guestMarkup,
      herdShareMarkup: snapshot.profile.herdShareMarkup,
      snapMarkup: snapshot.profile.snapMarkup,
      sale: toBooleanLabel(snapshot.profile.onSale),
      saleDiscount: snapshot.profile.saleDiscount,
      packageCount: snapshot.packageRows.length,
      description: product.description || "",
      track_inventory: toBooleanLabel(Boolean(product.trackInventory)),
      visible: toBooleanLabel(Boolean(product.visible)),
      remoteSyncStatus: snapshot.profile.remoteSyncStatus || "",
      remoteSyncedAt: formatDateTime(snapshot.profile.remoteSyncedAt)
    };

    sheetValues.push(
      ORDERED_COLUMN_NAMES.map((column) => toSheetValue(rowValues[column]))
    );
  }

  return {
    sheetValues,
    rowCount: Math.max(sheetValues.length - 1, 0),
    vendorNames: [...matchedVendorNames].sort((left, right) => left.localeCompare(right))
  };
}

export async function exportMasterPricelist({
  nodeEnv = process.env.NODE_ENV || "production",
  dryRun = false,
  skipGoogle = false,
  vendorNameMatcher = null,
  spreadsheetId = process.env.GOOGLE_SHEETS_SPREADSHEET_ID || "",
  tabName = process.env.GOOGLE_SHEETS_TAB_NAME || "prices"
} = {}) {
  const spreadsheetSummary = spreadsheetId
    ? `${spreadsheetId} (tab: ${tabName})`
    : "Not configured";

  const { sheetValues, rowCount, vendorNames } = await buildSheetValues({ vendorNameMatcher });
  const vendorSummary = vendorNames.length ? vendorNames.join(", ") : "All vendors";
  const introductionValues = buildIntroductionValues({
    syncTimeUtc: new Date().toISOString(),
    environment: nodeEnv,
    spreadsheetSummary,
    vendorSummary
  });

  if (dryRun || skipGoogle) {
    return {
      mode: dryRun ? "dry-run" : "skip-google",
      nodeEnv,
      spreadsheetSummary,
      vendorNames,
      rowCount,
      sampleRows: sheetValues.slice(0, 6)
    };
  }

  await syncPricelistToGoogleSheet(sheetValues, introductionValues);
  return {
    mode: "google-sync",
    nodeEnv,
    spreadsheetSummary,
    vendorNames,
    rowCount
  };
}

async function main() {
  const envFile = resolveFromRepoRoot(getArg("env-file") || ".env");
  const nodeEnv =
    getArg("node-env") ||
    (path.basename(envFile).match(/^\.env\.(.+)$/) || [])[1] ||
    process.env.NODE_ENV ||
    "production";
  const dryRun = hasFlag("dry-run");
  const skipGoogle = hasFlag("skip-google");

  dotenv.config({ path: envFile });

  const summary = await exportMasterPricelist({
    nodeEnv,
    dryRun,
    skipGoogle
  });

  if (dryRun || skipGoogle) {
    console.log(
      JSON.stringify(
        {
          ...summary,
          envFile
        },
        null,
        2
      )
    );
    return;
  }

  console.log(`Exported ${summary.rowCount} rows to Google Sheets.`);
}

const isDirectExecution =
  process.argv[1] && path.resolve(process.argv[1]) === __filename;

if (isDirectExecution) {
  main().catch((error) => {
    console.error(error?.message || error);
    process.exit(1);
  });
}
